import "./globals.css";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Track Resi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <link rel="icon" href="/divisi.png" sizes="any" />
        <header className="bg-gray-900 text-white p-4 flex justify-between sm:px-40">
          <Link href={`/`}>
            <Image src={`/divisi.png`} width={90} height={50} />
          </Link>
          <Image src={`/brawijaya.png`} width={50} height={50} />
        </header>
        {children}
        <footer className="bg-gray-900 text-white p-4 text-center">
          © Brawijaya Archivum est Potentia. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
